import React, { useState } from 'react';
import { Drink, SaleEntry } from '../types';
import { Citrus, Award, Search, ChevronDown, BarChart2 } from 'lucide-react';

interface ProductAnalyticsProps {
  drinks: Drink[];
  allSales: SaleEntry[];
}

export type TimeRange = 'today' | '7d' | '30d' | 'all';

export const ProductAnalytics: React.FC<ProductAnalyticsProps> = ({ drinks, allSales }) => {
  const [selectedDrinkId, setSelectedDrinkId] = useState<string>(drinks[0]?.id || '');
  const [compareDrinkId2, setCompareDrinkId2] = useState<string>('');
  const [compareDrinkId3, setCompareDrinkId3] = useState<string>('');
  const [timeRange, setTimeRange] = useState<TimeRange>('7d');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const selectedDrink: Drink | undefined = drinks.find((d) => d.id === selectedDrinkId) || drinks[0];
  const compareDrink2: Drink | undefined = drinks.find((d) => d.id === compareDrinkId2);
  const compareDrink3: Drink | undefined = drinks.find((d) => d.id === compareDrinkId3);

  const filteredDrinks = drinks.filter((d) =>
    d.name.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Helper to filter sales by time range
  const getTodayId = () => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  };

  const todayId = getTodayId();

  const filterSalesByTimeRange = (salesList: SaleEntry[]) => {
    return salesList.filter((s) => {
      if (s.voided) return false;
      if (timeRange === 'today') return s.dayId === todayId;
      if (timeRange === '7d' || timeRange === '30d') {
        const daysLimit = timeRange === '7d' ? 7 : 30;
        const cutoff = new Date();
        cutoff.setDate(cutoff.getDate() - daysLimit);
        const cutoffStr = `${cutoff.getFullYear()}-${String(cutoff.getMonth() + 1).padStart(2, '0')}-${String(cutoff.getDate()).padStart(2, '0')}`;
        return s.dayId >= cutoffStr;
      }
      return true; // 'all'
    });
  };

  // Active Product Stats in selected time range
  const activeProductSales = filterSalesByTimeRange(
    allSales.filter((s) => s.drinkId === selectedDrink?.id)
  );

  const totalQuantity = activeProductSales.length;
  const grossRevenue = activeProductSales.reduce((sum, s) => sum + s.priceMAD, 0);
  const ingredientCost = selectedDrink ? totalQuantity * selectedDrink.costToMakeMAD : 0;
  const netRevenue = grossRevenue - ingredientCost; // Net Profit Margin generated by this drink!

  // Group sales by dayId for selected drink
  const salesByDay: Record<string, { quantity: number; revenueMAD: number }> = {};
  activeProductSales.forEach((s) => {
    if (!salesByDay[s.dayId]) {
      salesByDay[s.dayId] = { quantity: 0, revenueMAD: 0 };
    }
    salesByDay[s.dayId].quantity += 1;
    salesByDay[s.dayId].revenueMAD += s.priceMAD;
  });

  const dailyBreakdown = Object.entries(salesByDay)
    .map(([dayId, data]) => ({ dayId, ...data }))
    .sort((a, b) => b.quantity - a.quantity);

  const peakDay = dailyBreakdown[0];

  // MULTI-PRODUCT COMPARISON CALCULATIONS
  const compProducts: { drink?: Drink; color: string; label: string }[] = [
    { drink: selectedDrink, color: '#10b981', label: '1. ' + (selectedDrink?.name || '') },
    ...(compareDrink2 ? [{ drink: compareDrink2, color: '#f59e0b', label: '2. ' + compareDrink2.name }] : []),
    ...(compareDrink3 ? [{ drink: compareDrink3, color: '#06b6d4', label: '3. ' + compareDrink3.name }] : []),
  ];

  // Unique list of dates in the time range across all compared products
  const compSales = filterSalesByTimeRange(allSales);
  const allDatesInRange = Array.from(
    new Set(compSales.map((s) => s.dayId))
  ).sort();

  // Scale bounds for SVG multi-product comparison chart
  const maxCompVolume = Math.max(
    ...allDatesInRange.flatMap((dayId) =>
      compProducts.map((p) =>
        compSales.filter((s) => s.drinkId === p.drink?.id && s.dayId === dayId).length
      )
    ),
    5
  );

  const chartWidth = 500;
  const chartHeight = 160;
  const paddingX = 25;
  const paddingY = 20;

  const datesCount = allDatesInRange.length;

  const getX = (idx: number) => {
    if (datesCount <= 1) return chartWidth / 2;
    return paddingX + (idx / (datesCount - 1)) * (chartWidth - paddingX * 2);
  };

  const getY = (val: number) => {
    const usableHeight = chartHeight - paddingY * 2;
    return chartHeight - paddingY - (val / maxCompVolume) * usableHeight;
  };

  return (
    <div className="space-y-4">
      {/* Header & Product Dropdown */}
      <div className="bg-stone-900 border border-stone-800 p-4 rounded-2xl space-y-3 shadow-lg">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-stone-800 pb-3">
          <div>
            <h3 className="font-bold text-stone-100 text-sm flex items-center gap-2">
              <Citrus className="w-5 h-5 text-emerald-400" />
              <span>Product Consumption & Net Revenue Analytics</span>
            </h3>
            <p className="text-xs text-stone-400 mt-0.5">
              Select product, choose time range, and compare multiple drinks side-by-side
            </p>
          </div>

          {/* Time Range Selector */}
          <div className="flex items-center gap-1 bg-stone-950 p-1 rounded-xl border border-stone-800 text-xs">
            {(['today', '7d', '30d', 'all'] as const).map((r) => (
              <button
                key={r}
                onClick={() => setTimeRange(r)}
                className={`px-2.5 py-1 rounded-lg uppercase font-bold transition-all ${
                  timeRange === r
                    ? 'bg-emerald-600 text-white shadow'
                    : 'text-stone-400 hover:text-stone-200'
                }`}
              >
                {r === 'today' ? 'Today' : r === '7d' ? '7 Days' : r === '30d' ? '30 Days' : 'All Time'}
              </button>
            ))}
          </div>
        </div>

        {/* Primary Product Dropdown & Search Filter */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
          <div>
            <label className="text-xs font-bold text-stone-300 block mb-1 uppercase tracking-wider">
              Primary Product:
            </label>
            <div className="relative">
              <select
                value={selectedDrinkId}
                onChange={(e) => setSelectedDrinkId(e.target.value)}
                className="w-full bg-stone-950 border-2 border-emerald-500/80 text-emerald-300 font-bold text-sm rounded-xl px-3.5 py-2.5 appearance-none focus:outline-none focus:border-emerald-400 cursor-pointer pr-10"
              >
                {filteredDrinks.map((d) => (
                  <option key={d.id} value={d.id} className="bg-stone-900 text-stone-100 font-medium">
                    {d.name} — ({d.category.toUpperCase()}) {d.defaultPriceMAD} DH
                  </option>
                ))}
              </select>
              <ChevronDown className="w-5 h-5 text-emerald-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>

          <div>
            <label className="text-xs font-medium text-stone-400 block mb-1">
              Filter Product List:
            </label>
            <div className="relative">
              <Search className="w-4 h-4 text-stone-500 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search drink name..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-stone-950 border border-stone-700 rounded-xl pl-9 pr-3 py-2 text-xs text-stone-100 placeholder-stone-500 focus:outline-none focus:border-emerald-500"
              />
            </div>
          </div>
        </div>
      </div>

      {/* SELECTED PRODUCT FINANCIAL METRICS FOR TIME RANGE */}
      {selectedDrink && (
        <div className="bg-stone-900 border border-stone-800 p-4 rounded-2xl space-y-3 shadow-lg">
          <div className="flex items-center justify-between border-b border-stone-800 pb-2">
            <div>
              <span className="font-extrabold text-base text-stone-100">{selectedDrink.name}</span>
              <span className="text-[10px] uppercase font-mono bg-stone-800 text-stone-400 px-1.5 py-0.5 rounded ml-2">
                {selectedDrink.category}
              </span>
            </div>
            <span className="text-xs font-bold text-amber-400 font-mono uppercase bg-amber-950/60 px-2.5 py-1 rounded-lg border border-amber-800">
              Range: {timeRange.toUpperCase()}
            </span>
          </div>

          {/* 4 Financial Metric Cards: Quantity, Gross Revenue, Ingredient Cost, NET REVENUE */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5 text-xs font-mono">
            <div className="bg-stone-950 p-3 rounded-xl border border-stone-850">
              <span className="text-stone-400 block text-[10px] uppercase">Units Sold</span>
              <span className="font-black text-stone-100 text-lg">{totalQuantity} drinks</span>
            </div>

            <div className="bg-stone-950 p-3 rounded-xl border border-stone-850">
              <span className="text-stone-400 block text-[10px] uppercase">Gross Revenue</span>
              <span className="font-black text-emerald-400 text-lg">{grossRevenue} MAD</span>
            </div>

            <div className="bg-stone-950 p-3 rounded-xl border border-stone-850">
              <span className="text-stone-400 block text-[10px] uppercase">Ingredient Cost</span>
              <span className="font-bold text-rose-400 text-sm">-{ingredientCost.toFixed(1)} MAD</span>
            </div>

            <div className="bg-emerald-950/60 border border-emerald-500/50 p-3 rounded-xl">
              <span className="text-emerald-300 font-bold block text-[10px] uppercase">NET REVENUE / MARGIN</span>
              <span className="font-black text-emerald-300 text-xl">{netRevenue.toFixed(1)} MAD</span>
            </div>
          </div>

          {/* Peak Sales Day Highlight */}
          {peakDay && (
            <div className="bg-gradient-to-r from-emerald-950/80 via-stone-950 to-stone-950 border border-emerald-500/40 p-3 rounded-xl flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Award className="w-4 h-4 text-emerald-400 shrink-0" />
                <span className="text-xs text-stone-300">
                  Peak Sales Day in range: <strong className="text-stone-100 font-mono">{peakDay.dayId}</strong>
                </span>
              </div>
              <div className="text-right font-mono">
                <span className="text-emerald-300 font-bold text-sm">{peakDay.quantity} sold ({peakDay.revenueMAD} MAD)</span>
              </div>
            </div>
          )}
        </div>
      )}

      {/* MULTI-PRODUCT COMPARISON CHART (Compare 2 or 3 Products) */}
      <div className="bg-stone-900 border border-stone-800 p-4 rounded-2xl space-y-3 shadow-lg">
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-stone-800 pb-2.5">
          <div className="flex items-center gap-2">
            <BarChart2 className="w-5 h-5 text-amber-400" />
            <h4 className="font-bold text-sm text-stone-100">Compare 2 or 3 Products Side-by-Side</h4>
          </div>
          <span className="text-xs text-stone-400">Sales Volume Chart ({timeRange.toUpperCase()})</span>
        </div>

        {/* Dropdowns to select Product 2 and Product 3 */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
          <div>
            <label className="text-stone-400 block mb-1 font-semibold">Compare with Product 2 (Amber Line):</label>
            <select
              value={compareDrinkId2}
              onChange={(e) => setCompareDrinkId2(e.target.value)}
              className="w-full bg-stone-950 border border-amber-500/60 text-amber-300 font-medium rounded-xl px-3 py-2 focus:outline-none"
            >
              <option value="">-- None (Select Product 2) --</option>
              {drinks.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name} ({d.defaultPriceMAD} DH)
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-stone-400 block mb-1 font-semibold">Compare with Product 3 (Cyan Line):</label>
            <select
              value={compareDrinkId3}
              onChange={(e) => setCompareDrinkId3(e.target.value)}
              className="w-full bg-stone-950 border border-cyan-500/60 text-cyan-300 font-medium rounded-xl px-3 py-2 focus:outline-none"
            >
              <option value="">-- None (Select Product 3) --</option>
              {drinks.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.name} ({d.defaultPriceMAD} DH)
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Legend */}
        <div className="flex flex-wrap items-center gap-4 text-xs font-mono pt-1">
          {compProducts.map((p) => {
            const count = filterSalesByTimeRange(allSales.filter((s) => s.drinkId === p.drink?.id)).length;
            return (
              <div key={p.label} className="flex items-center gap-1.5 bg-stone-950 px-2.5 py-1 rounded-lg border border-stone-800">
                <span className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: p.color }} />
                <span className="text-stone-200 font-bold">{p.label}:</span>
                <span className="text-amber-300 font-extrabold">{count} sold</span>
              </div>
            );
          })}
        </div>

        {/* Multi-Product Linear SVG Chart */}
        {allDatesInRange.length > 0 ? (
          <div className="relative pt-3">
            <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="w-full h-44 overflow-visible select-none">
              {/* Grid Lines */}
              {[0.25, 0.5, 0.75, 1].map((ratio) => {
                const y = getY(maxCompVolume * ratio);
                return (
                  <line
                    key={ratio}
                    x1={paddingX}
                    y1={y}
                    x2={chartWidth - paddingX}
                    y2={y}
                    stroke="#27272a"
                    strokeDasharray="3 3"
                    strokeWidth="1"
                  />
                );
              })}

              {/* Render Polyline for each product */}
              {compProducts.map((p) => {
                if (!p.drink) return null;
                const pointsStr = allDatesInRange
                  .map((dayId, idx) => {
                    const vol = compSales.filter((s) => s.drinkId === p.drink?.id && s.dayId === dayId).length;
                    return `${getX(idx)},${getY(vol)}`;
                  })
                  .join(' ');

                return (
                  <g key={p.drink.id}>
                    <polyline
                      fill="none"
                      stroke={p.color}
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      points={pointsStr}
                    />
                    {allDatesInRange.map((dayId, idx) => {
                      const vol = compSales.filter((s) => s.drinkId === p.drink?.id && s.dayId === dayId).length;
                      return (
                        <circle
                          key={dayId}
                          cx={getX(idx)}
                          cy={getY(vol)}
                          r="4"
                          fill={p.color}
                          stroke="#09090b"
                          strokeWidth="2"
                        />
                      );
                    })}
                  </g>
                );
              })}
            </svg>

            {/* X-Axis Dates */}
            <div className="flex justify-between px-2 pt-1 font-mono text-[9px] text-stone-500">
              {allDatesInRange.map((dayId) => (
                <span key={dayId}>{dayId.slice(5)}</span>
              ))}
            </div>
          </div>
        ) : (
          <p className="text-xs text-stone-500 text-center py-4">No sales recorded for comparison in this time range.</p>
        )}
      </div>

      {/* Daily Consumption Breakdown Table (Ranked High to Low) */}
      <div className="bg-stone-900 border border-stone-800 p-4 rounded-2xl space-y-3 shadow-lg">
        <h4 className="font-bold text-xs text-stone-300 uppercase tracking-wider border-b border-stone-800 pb-2">
          Daily Consumption Breakdown for {selectedDrink?.name} ({timeRange.toUpperCase()})
        </h4>

        {dailyBreakdown.length === 0 ? (
          <p className="text-xs text-stone-500 text-center py-4">No sales recorded for this drink in the selected time range.</p>
        ) : (
          <div className="space-y-1.5 max-h-64 overflow-y-auto">
            {dailyBreakdown.map((item, index) => (
              <div
                key={item.dayId}
                className="bg-stone-950 px-3.5 py-2.5 rounded-xl border border-stone-850 flex items-center justify-between text-xs font-mono"
              >
                <div className="flex items-center gap-2">
                  <span className="w-5 h-5 rounded-lg bg-stone-850 text-stone-400 flex items-center justify-center text-[10px] font-bold">
                    #{index + 1}
                  </span>
                  <span className="font-bold text-stone-200">{item.dayId}</span>
                </div>

                <div className="flex items-center gap-4">
                  <span className="font-black text-amber-300 text-sm">{item.quantity} sold</span>
                  <span className="font-bold text-emerald-400">{item.revenueMAD} MAD</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
